version: "3.7"

services:
  postgres:
    container_name: bot_postgres_container
    image: postgres:16
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped